version: '3.1'
services: 
  web:
    image: nginx
    build: .
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:8080"
    environment:
     - NGINX_HOST=lenschess.com
     - NGINX_PORT=80