

version: '3.1'

services: 
  web:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "5000:80"
    environment:
     - NGINX_HOST=lenschess.com
     - NGINX_PORT=80